# Generated by Django 4.0.1 on 2022-02-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_movie_linkname'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='stars',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.CharField(max_length=1000),
        ),
    ]
